title: Laura Toribio Celestino
description: Bioinformatics | Data Science | R&D
logo: /assets/images/LaboraTORIbio_logo.png
#show_downloads: true
#github:
#  is_project_page: true
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme