title: Laura Toribio Celestino
description: Bioinformatics | Data Science | R&D
logo: /assets/images/LaboraTORIbio_logo.png

linkedin: laura-toribio-celestino
github: LaboraTORIbio
email: lauratorcel@gmail.com
social-links-order: [linkedin, github, email]

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme