title: Laura Toribio Celestino
description: Bioinformatician &  Data Scientist
logo: /assets/images/LaboraTORIbio_logo.png

linkedin: laura-toribio-celestino
github: LaboraTORIbio
email: lauratorcel@gmail.com

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme